name: CI Tests

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Install uv and activate a virtual environment
      uses: astral-sh/setup-uv@v6
      with:
        # Install the specific version of uv that we currently use
        version: "0.6.14"
        enable-cache: true
        activate-environment: true

    - name: Set up Python  # this is said to be faster than uv python install
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Setup and run tests
      shell: bash
      run: |
        # Create and activate virtual environment
        # uv venv .venv
        # source .venv/bin/activate

        # Install dependencies
        # uv pip install --upgrade pip
        # uv pip install django pytest pytest-django ruff

        # Run tests and linter
        uv run pytest apt_app/tests.py -v
        # uvx ruff check .
