name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        # Create and activate virtual environment
        uv venv .venv
        source .venv/bin/activate

        # Install dependencies
        uv pip install --upgrade pip
        uv pip install django

    - name: Run tests
      run: |
        # Activate the virtual environment again
        source .venv/bin/activate
        python manage.py test apt_app
