# Generated by Django 5.2 on 2025-05-01 19:35

import apt_app.mixins
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("grocery", "Grocery Store"),
                            ("pharmacy", "Pharmacy"),
                            ("restaurant", "Restaurant"),
                            ("cafe", "Cafe"),
                            ("bar", "Bar"),
                            ("hospital", "Hospital"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="apt_app_ame_locatio_5dcd07_gist"
                    )
                ],
            },
            bases=(apt_app.mixins.LocationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Crime",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("date", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OFFENSE INVOLVING CHILDREN", "Offense Involving Children"),
                            ("NARCOTICS", "Narcotics"),
                            ("CRIM SEXUAL ASSAULT", "Crim Sexual Assault"),
                            ("CRIMINAL DAMAGE", "Criminal Damage"),
                            ("THEFT", "Theft"),
                            ("BURGLARY", "Burglary"),
                            ("SEX OFFENSE", "Sex Offense"),
                            ("ROBBERY", "Robbery"),
                            ("MOTOR VEHICLE THEFT", "Motor Vehicle Theft"),
                            ("BATTERY", "Battery"),
                            ("HOMICIDE", "Homicide"),
                            ("CRIMINAL SEXUAL ASSAULT", "Criminal Sexual Assault"),
                            ("OTHER OFFENSE", "Other Offense"),
                            ("WEAPONS VIOLATION", "Weapons Violation"),
                            ("DECEPTIVE PRACTICE", "Deceptive Practice"),
                            ("STALKING", "Stalking"),
                            ("CRIMINAL TRESPASS", "Criminal Trespass"),
                            ("ASSAULT", "Assault"),
                            ("PROSTITUTION", "Prostitution"),
                            ("KIDNAPPING", "Kidnapping"),
                            ("ARSON", "Arson"),
                            (
                                "CONCEALED CARRY LICENSE VIOLATION",
                                "Concealed Carry License Violation",
                            ),
                            (
                                "INTERFERENCE WITH PUBLIC OFFICER",
                                "Interference with Public Officer",
                            ),
                            ("PUBLIC PEACE VIOLATION", "Public Peace Violation"),
                            ("LIQUOR LAW VIOLATION", "Liquor Law Violation"),
                            ("INTIMIDATION", "Intimidation"),
                            ("HUMAN TRAFFICKING", "Human Trafficking"),
                            ("GAMBLING", "Gambling"),
                            ("OBSCENITY", "Obscenity"),
                            ("PUBLIC INDECENCY", "Public Indecency"),
                            ("NON-CRIMINAL", "Non-Criminal"),
                            ("OTHER NARCOTIC VIOLATION", "Other Narcotic Violation"),
                            ("RITUALISM", "Ritualism"),
                            ("DOMESTIC VIOLENCE", "Domestic Violence"),
                            (
                                "NON-CRIMINAL (SUBJECT SPECIFIED)",
                                "Non-Criminal (Subject Specified)",
                            ),
                            ("NON - CRIMINAL", "Non - Criminal"),
                        ],
                        default="NON - CRIMINAL",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="apt_app_cri_locatio_8e2576_gist"
                    )
                ],
            },
            bases=(apt_app.mixins.LocationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="apt_app_pro_locatio_24fc0f_gist"
                    )
                ],
            },
            bases=(apt_app.mixins.LocationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("inspection_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("result", models.CharField(max_length=50)),
                ("notes", models.TextField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apt_app.property"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteProperty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("custom_name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_saved", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apt_app.property"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransitStop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cta", "CTA"),
                            ("metra", "Metra"),
                            ("shuttle", "UChicago Shuttle"),
                            ("divvy", "Divvy Bike"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["location"], name="apt_app_tra_locatio_ff5248_gist"
                    )
                ],
            },
            bases=(apt_app.mixins.LocationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TransitRoute",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cta", "CTA"),
                            ("metra", "Metra"),
                            ("shuttle", "UChicago Shuttle"),
                            ("divvy", "Divvy Bike"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("geometry", django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stops", models.ManyToManyField(related_name="routes", to="apt_app.transitstop")),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["geometry"], name="apt_app_tra_geometr_7bcbf1_gist"
                    )
                ],
            },
        ),
    ]
