# Generated by Django 5.2 on 2025-05-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0002_amenity_crime_property_inspection_favoriteproperty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("summary", models.JSONField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apt_app.property"
                    ),
                ),
            ],
        ),
    ]
