# Generated by Django 5.2 on 2025-05-07 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0003_inspectionsummary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectionsummary",
            name="property",
        ),
    ]
