# Generated by Django 5.2 on 2025-05-14 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0003_property_bus_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitroute',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
