# Generated by Django 5.2 on 2025-05-07 17:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0004_remove_inspectionsummary_property"),
    ]

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("violation_id", models.CharField(max_length=10)),
                ("violation_last_modified_date", models.DateField()),
                ("violation_date", models.DateField()),
                ("violation_code", models.CharField(max_length=20)),
                ("violation_status", models.CharField(max_length=10)),
                ("violation_status_date", models.DateField()),
                ("violation_description", models.TextField()),
                ("violation_location", models.CharField(max_length=20)),
                ("violation_inspector_comments", models.TextField()),
                ("violation_ordinance", models.TextField()),
                ("inspector_id", models.CharField(max_length=20)),
                ("inspection_number", models.IntegerField()),
                ("inspection_status", models.CharField(max_length=10)),
                ("inspection_waived", models.CharField(max_length=5)),
                ("inspection_category", models.CharField(max_length=10)),
                ("department_bureau", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("street_number", models.IntegerField()),
                ("street_direction", models.CharField(max_length=5)),
                ("street_name", models.CharField(max_length=20)),
                ("street_type", models.CharField(max_length=10)),
                ("property_group", models.IntegerField()),
                ("ssa", models.CharField(max_length=10)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
