# Generated by Django 5.2 on 2025-05-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0004_alter_transitroute_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitroute',
            name='id',
        ),
        migrations.AddField(
            model_name='transitroute',
            name='route_id',
            field=models.CharField(default='TEMP', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
