# Generated by Django 5.2 on 2025-05-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0005_violation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="violation",
            name="id",
        ),
        migrations.AlterField(
            model_name="violation",
            name="violation_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="violation",
            name="violation_status_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
