# Generated by Django 5.2 on 2025-05-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0006_remove_violation_id_alter_violation_violation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violation",
            name="department_bureau",
            field=models.CharField(max_length=50),
        ),
    ]
