# Generated by Django 5.2 on 2025-05-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0007_alter_violation_department_bureau"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violation",
            name="violation_location",
            field=models.CharField(max_length=50),
        ),
    ]
