# Generated by Django 5.2 on 2025-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apt_app", "0009_alter_violation_violation_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violation",
            name="violation_location",
            field=models.TextField(),
        ),
    ]
