# Generated by Django 5.2.1 on 2025-05-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0005_remove_transitroute_id_transitroute_route_id'),
        ('apt_app', '0010_alter_violation_violation_location'),
    ]

    operations = [
    ]
