# Generated by Django 5.2.1 on 2025-05-22 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0011_merge_20250522_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='inspection_category',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_price', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt_app.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_property',
            },
        ),
        migrations.DeleteModel(
            name='FavoriteProperty',
        ),
    ]
