# Generated by Django 5.2.1 on 2025-05-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0011_merge_20250522_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='violation',
            name='inspection_category',
            field=models.CharField(max_length=20),
        ),
    ]
