# Generated by Django 5.2.1 on 2025-05-25 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def delete_favorite_property_if_exists(apps, schema_editor):
    """Delete FavoriteProperty table only if it exists"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'apt_app_favoriteproperty'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            # Drop the table if it exists
            cursor.execute("DROP TABLE apt_app_favoriteproperty CASCADE;")


def reverse_delete_favorite_property(apps, schema_editor):
    """Reverse operation - this is a no-op since we can't recreate the dropped table"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0012_amenity_address_alter_violation_inspection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='Unknown Address', max_length=512)),
                ('custom_name', models.CharField(blank=True, max_length=512, null=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rent_price', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apt_app.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            delete_favorite_property_if_exists,
            reverse_code=reverse_delete_favorite_property
        ),
        migrations.AddIndex(
            model_name='savedproperty',
            index=models.Index(fields=['address'], name='apt_app_sav_address_9e6c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='savedproperty',
            index=models.Index(fields=['is_deleted'], name='apt_app_sav_is_dele_e03d1d_idx'),
        ),
    ]