# Generated by Django 5.2.1 on 2025-05-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0012_alter_violation_inspection_category_savedproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=512),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='custom_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
