# Generated by Django 5.2.1 on 2025-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0013_savedproperty_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savedproperty',
            index=models.Index(fields=['address'], name='apt_app_sav_address_9e6c0c_idx'),
        ),
        migrations.AlterModelTable(
            name='savedproperty',
            table=None,
        ),
    ]
