# Generated by Django 5.2.1 on 2025-05-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0013_savedproperty_delete_favoriteproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='groceries',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
