# Generated by Django 5.2.1 on 2025-05-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0014_alter_property_groceries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproperty',
            old_name='property',
            new_name='property_obj',
        ),
    ]
