# Generated by Django 5.2.1 on 2025-05-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0014_savedproperty_apt_app_sav_address_9e6c0c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='savedproperty',
            index=models.Index(fields=['is_deleted'], name='apt_app_sav_is_dele_e03d1d_idx'),
        ),
    ]
