# Generated by Django 5.2.1 on 2025-05-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0015_savedproperty_deleted_at_savedproperty_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproperty',
            old_name='property',
            new_name='property_obj',
        ),
    ]
