# Generated by Django 5.2.1 on 2025-05-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0016_rename_property_savedproperty_property_abcd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproperty',
            old_name='property_abcd',
            new_name='property_obj',
        ),
    ]
