# Generated by Django 5.2.1 on 2025-05-29 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_app', '0016_alter_amenity'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='favoriteproperty',
        #     name='property',
        # ),
        # migrations.RemoveField(
        #     model_name='favoriteproperty',
        #     name='user',
        # ),
        migrations.RemoveIndex(
            model_name='amenity',
            name='apt_app_ame_locatio_5dcd07_gist',
        ),
        migrations.AddField(
            model_name='inspectionsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionsummary',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspectionsummary',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apt_app.property'),
        ),
        migrations.AddField(
            model_name='inspectionsummary',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        # migrations.DeleteModel(
        #     name='FavoriteProperty',
        # ),
    ]
